# Generated by Django 4.2.2 on 2023-06-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
