# Generated by Django 4.2.3 on 2023-07-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipi_name', models.CharField(max_length=50)),
                ('receipi_desc', models.CharField(max_length=500)),
                ('reci_img', models.FileField(upload_to='receipi')),
            ],
        ),
    ]
